<?php use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;

$msg = Data::get('msg');
Layout::includeLayout('header') ?>

    <!-- Area de login -->
    <section id="login"> <!-- style="width:100%; text-align: center; -->
        <div class="container py-5">
            <div class="text-center pb-5">
                <h1 class="login-title text-dark">Login</h1>
                <p class="p-1 m-0 font-ubuntu text-black-50">Faça Login e divirta-se com o jogo!</p>
                <span class="font-ubuntu text-black-50">Eu ainda não tenho uma conta, <a href="<?= Url::toRoute('user/register')?>">Registar</a></span>
            </div>

            <div class="d-flex justify-content-center"> <!-- style="width: 400px; margin-left: 20% -->
                <form action="<?= Url::toRoute('user/login')?>" method="post" id="log-form"> <!-- enctype="multipart/form-data" -->
                    <div class="form-row my-4">
                        <div class="col">
                            <input type="email" required name="email" id="email" class="form-control" placeholder="Email*">
                        </div>
                    </div>

                    <div class="form-row my-4">
                        <div class="col">
                            <input type="password" required name="password" id="password" class="form-control" placeholder="Password*">
                        </div>
                    </div>

                    <div class="submit-btn text-center my-5">
                        <button type="submit" class="btn btn-warning rounded-pill text-dark px-5">Login</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
    <!-- #Area de login-->

<?php Layout::includeLayout('footer')?>