<?php

use ArmoredCore\WebObjects\Layout;

Layout::includeLayout('indexheader'); ?>
    <header id="head">
        <div class="container">
            <div class="row">
                <h1 class="lead"><b>WEBlogic Studio</b><br><small><b>Armored</b>Core v0.85</small><br>MVC Reference Framework</h1>
            </div>
        </div>
    </header>

    <div class="container text-center">
        <h1>HELLO WORLD</h1>
    </div>
<?php Layout::includeLayout('footer') ?>