<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\URL;

$engine = Data::get('ge');

Layout::includeLayout('header'); ?>
    <div id="page-container" style="margin-top: 100px">
        <div class="section_" id="content-wrap">
            <div>
                <h1 style="text-align: center; width: 100%;">Jogo</h1>
                <div style="margin: 29px; text-align: left">
                    <h1>Jogador - Pedro</h1>
                    <div>
                        <?php if (Session::has('gameEngine') && $engine->getEstadoJogo() == 2) {
                            $numeroBloqueadoP1 = $engine->tabuleiro->numeroBloqueioP1->getNumerosBloqueio();
                            for ($i = 1; $i < 10; $i++) {
                                if ($numeroBloqueadoP1[$i] == false) { ?>
                                    <a href="<?= URL::toRoute('jogo/seleciona', $i) ?>">
                                        <button class="btn btn-default" type="button"><?= $i ?></button>
                                    </a>
                                <?php } else { ?>
                                    <button disabled class="btn btn-default" type="button"><?= $i ?></button>
                                <?php } ?>
                            <?php } ?>
                        <?php } ?>
                    </div>
                </div>
            </div>
            <div class="text-center">
                <div>
                    <h1 style="float: left;margin-left: 100px;font-size: 100px;width: 112px;margin-top: 0;">20</h1>
                    <?php if (Session::has('gameEngine') && $engine->getEstadoJogo() == 2) { ?>
                        <!--<img src="<?= Asset::image($engine->tabuleiro->resultadoDado1 . '.png') ?>" width="112px"
                             style="margin-right: 15px;">-->
                        <h1 class= "semidado"><?php echo $engine->tabuleiro->resultadoDado1?></h1>

                    <!--<img src="<?= Asset::image($engine->tabuleiro->resultadoDado2 . '.png') ?>" width="112px">-->
                        <h1 class="semidado"><?php echo $engine->tabuleiro->resultadoDado2?></h1>
                    <?php } ?>

                    <h1 style="float: right;margin: 0;margin-right: 100px;width: 112px;font-size: 100px;">20</h1>
                </div>
                <div style="text-align: center; width: 100%; ">
                    <?php if (Session::has('gameEngine') && $engine->getEstadoJogo() == 1) { ?>
                        <a href="<?= URL::toRoute('jogo/rolardados') ?>">
                            <button class="btn btn-primary" type="button"
                                    style="margin-left: -210px; margin-top: 10px; ">
                                Roll Dice
                            </button>
                        </a>
                    <?php } ?>

                    <?php if (Session::has('gameEngine') && $engine->getEstadoJogo() == 0) { ?>
                        <a href="<?= Url::toRoute('jogo/iniciarjogo') ?>">
                            <button class="btn btn-primary" type="button" style=" margin-left: -210px; margin-top: 10px; ">
                                Iniciar Jogo
                            </button>
                        </a>
                    <?php } ?>

                </div>


            </div>
            <div>
                <div>
                    <div style="margin: 29px; text-align: right">
                        <div>
                            <button class="btn btn-default" type="button">1</button>
                            <button class="btn btn-default" type="button">2</button>
                            <button class="btn btn-default" type="button">3</button>
                            <button class="btn btn-default" type="button">4</button>
                            <button class="btn btn-default" type="button">5</button>
                            <button class="btn btn-default" type="button">6</button>
                            <button class="btn btn-default" type="button">7</button>
                            <button class="btn btn-default" type="button">8</button>
                            <button class="btn btn-default" type="button">9</button>
                        </div>
                        <h1>Jogador - Marco</h1>
                    </div>
                </div>
            </div>
        </div>
        <?php Layout::includeLayout('footer');
        Tracy\Debugger::barDump($engine);
        ?>
    </div>
 <!--   <header id="head">
        <div class="container">
            <div class="row">
                <h1 class="lead"><b>WEBlogic Studio</b><br><small><b>Armored</b>Core v0.85</small><br>MVC Reference Framework</h1>
            </div>
        </div>
    </header>

    <div class="container text-center">
        <h1>SHUT THE BOX</h1>
    </div>

    <div id="main" class="text-center" style="margin-top: 50px;">
        <div class="container">
            <div class="row col-md-4 col-md-offset-4">
                <div>
                <div class="col-xs-3">

                    <div>
                        <img src="<?= Asset::image('num1.png')?>" id="p1n1" alt="1">
                </div>
                    <div>
                        <img src="<?= Asset::image('num2.png')?>" id="p1n2" alt="2" style="margin-top: 5px;">
                    </div>
                    <div>
                        <img src="<?= Asset::image('num3.png')?>" id="p1n3" alt="3" style="margin-top: 5px;">
                    </div>
                    <div>
                        <img src="<?= Asset::image('num4.png')?>" id="p1n4" alt="4" style="margin-top: 5px;">
                    </div>
                    <div>
                        <img src="<?= Asset::image('num5.png')?>" id="p1n5" alt="5" style="margin-top: 5px;">
                    </div>
                    <div>
                        <img src="<?= Asset::image('num6.png')?>" id="p1n6" alt="6" style="margin-top: 5px;">
                    </div>
                    <div>
                        <img src="<?= Asset::image('num7.png')?>" id="p1n7" alt="7" style="margin-top: 5px;">
                    </div>
                    <div>
                        <img src="<?= Asset::image('num8.png')?>" id="p1n8" alt="8" style="margin-top: 5px;">
                    </div>
                    <div>
                        <img src="<?= Asset::image('num9.png')?>" id="p1n9" alt="9" style="margin-top: 5px;">
                    </div>
                </div>
                    <h1 style="float: left;margin-left: 100px;font-size: 100px;width: 112px;margin-top: 0;"></h1>
                <div class="col-xs-6">
                    <div class="row">
                        <div class="col-xs-6">
                            <div class="jogadores">
                                <img src="<?= Asset::image('human.png')?>" id="p1i" alt="Player" class="center-block">
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="jogadores">
                                <img src="<?= Asset::image('pc.png')?>" id="p2i" alt="Computer" class="center-block">
                            </div>
                        </div>
                    </div>

                    <div class="row" style="margin-top: 100px;">
                        <div class="col-xs-6">
                            <div>
                                <img src="<?= Asset::image('Box_Boarder.png')?>" id="p1p" alt="PontosP1">
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div>
                                <img src="<?= Asset::image('Box_Boarder.png')?>" id="p2p" alt="PontosP2">
                            </div>
                        </div>
                    </div>

                    <div class="row" style="margin-top: 75px;">
                        <div class="col-xs-12">
                            <input id="btnDados" value="Rodar Dados" type="button" class="btn btn-primary center-block" disabled="">
                        </div>
                    </div>
                    <div class="row center-block" style="margin-top: 80px;">
                        <div class="col-xs-6">
                            <div>
                                <img id="dice1" class="img-responsive die" src="<?= Asset::image('dieWhite_border1.png')?>" alt="Die 1">
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div>
                                <img id="dice2" class="img-responsive die" src="<?= Asset::image('dieRed_border1.png')?>" alt="Die 1">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xs-3">
                    <div>
                        <img src="<?= Asset::image('num1.png')?>" id="p2n1" alt="1">
                    </div>
                    <div>
                        <img src="<?= Asset::image('num2.png')?>" id="p2n2" alt="2" style="margin-top: 5px;">
                    </div>
                    <div>
                        <img src="<?= Asset::image('num3.png')?>" id="p2n3" alt="3" style="margin-top: 5px;">
                    </div>
                    <div>
                        <img src="<?= Asset::image('num4.png')?>" id="p2n4" alt="4" style="margin-top: 5px;">
                    </div>
                    <div>
                        <img src="<?= Asset::image('num5.png')?>" id="p2n5" alt="5" style="margin-top: 5px;">
                    </div>
                    <div>
                        <img src="<?= Asset::image('num6.png')?>" id="p2n6" alt="6" style="margin-top: 5px;">
                    </div>
                    <div>
                        <img src="<?= Asset::image('num7.png')?>" id="p2n7" alt="7" style="margin-top: 5px;">
                    </div>
                    <div>
                        <img src="<?= Asset::image('num8.png')?>" id="p2n8" alt="8" style="margin-top: 5px;">
                    </div>
                    <div>
                        <img src="<?= Asset::image('num9.png')?>" id="p2n9" alt="9" style="margin-top: 5px;">
                    </div>
                </div>

            </div>
        </div>
    </div>-->